import { PLAYER_CLASSES } from "../../Menu/types";
import { cursedChestScene } from "../../scene/CursedTreasureScene";
import { dueyIntroScene } from "../../scene/Duey/duey";
import { goldRichieIntro, goldRichieMercenaries, goldRichieRetrade } from "../../scene/GoldRichie/GoldRichie";
import { noobIntro, noobRivalWarrior } from "../../scene/Noob";
import { wantedPosterScene } from "../../scene/WantedPoster/wantedPosterScene";
import { bobSnailScene } from "../../scene/bob";
import { mesoThiefScene } from "../../scene/misc";
import { EventScene } from "../../scene/types";
import { wanderingSmithScene } from "../../scene/wanderingBlacksmithScene";
import {
    adamantiumPlate,
    adventurerCape,
    alligatorTube,
    amethyst,
    ancientTreeSap,
    aquamarine,
    ballerCane,
    battleShield,
    bigMesoItem,
    blueJeanShorts,
    blueSaunaRobe,
    boneHelm,
    bouquet,
    brick,
    cactus,
    clubMembership,
    coffeePot,
    cursedDoll,
    deckOfCards,
    diamond,
    diamondOre,
    drakeBlood,
    estherShield,
    fairyWing,
    fishSpear,
    flamingFeather,
    garnet,
    greenBambooHat,
    guideBook,
    ironMace,
    koreanFan,
    leatherSandals,
    luckSack,
    mesoItem,
    nependeathSap,
    panlid,
    pieceOfIce,
    pigIllustrated,
    pigsRibbonItem,
    plunger,
    rabbitFoot,
    redHeadband,
    redHeartedEarrings,
    redWhip,
    respawnToken,
    risingStar,
    safetyCharm,
    snailStompers,
    spectrumGoggles,
    tShirt,
    starEarrings,
    starfallMagicSquare,
    steely,
    stolenFence,
    sunshinePan,
    sword,
    tauromacisHorn,
    taurospearHorn,
    theBackpack,
    tofuSpecial,
    topaz,
    tortieShell,
    wildKargoEye,
    workGloves,
    icarusCape,
    bloodMask,
    peach,
    incenseLeaves,
    toyHammer,
    hugeMesoItem,
} from "./../../item/items";

export const events: EventScene[] = [
    goldRichieIntro,
    goldRichieMercenaries,
    goldRichieRetrade,
    dueyIntroScene,
    bobSnailScene,
    noobIntro,
    noobRivalWarrior,
    wantedPosterScene,
    mesoThiefScene,
    cursedChestScene,
    wanderingSmithScene,
];

/**
 * Items acquirable from elite/boss battles and treasure boxes
 */
export const ITEMS = [
    safetyCharm,
    drakeBlood,
    nependeathSap,
    coffeePot,
    respawnToken,
    sunshinePan,
    stolenFence,
    panlid,
    luckSack,
    adventurerCape,
    guideBook,
    alligatorTube,
    cactus,
    pieceOfIce,
    aquamarine,
    boneHelm,
    amethyst,
    topaz,
    redWhip,
    garnet,
    ironMace,
    fishSpear,
    pigsRibbonItem,
    ballerCane,
    greenBambooHat,
    koreanFan,
    risingStar,
    bouquet,
    starfallMagicSquare,
    cursedDoll,
    workGloves,
    snailStompers,
    clubMembership,
    diamond,
    tortieShell,
    estherShield,
    spectrumGoggles,
    redHeartedEarrings,
    fairyWing,
    ancientTreeSap,
    blueSaunaRobe,
    steely,
    tauromacisHorn,
    taurospearHorn,
    brick,
    adamantiumPlate,
    wildKargoEye,
    pigIllustrated,
    deckOfCards,
    flamingFeather,
    diamondOre,
    plunger,
    tofuSpecial,
    battleShield,
    sword,
    rabbitFoot,
    blueJeanShorts,
    tShirt,
    leatherSandals,
    redHeadband,
    mesoItem,
    bigMesoItem,
    hugeMesoItem,
    theBackpack,
    icarusCape,
    peach,
    incenseLeaves,
    toyHammer,
];

export const CLASS_ITEMS = {
    [PLAYER_CLASSES.WARRIOR]: [bloodMask],
    [PLAYER_CLASSES.MAGICIAN]: [starEarrings],
};
