import { dueyScenario } from "../../scene/Duey/duey";
import { goldRichieMerchant } from "../../scene/GoldRichie/GoldRichie";
import { noob } from "../../scene/Noob";
import {
    alligatorTube,
    amethyst,
    aquamarine,
    ballerCane,
    boneHelm,
    bouquet,
    cactus,
    coffeePot,
    cursedDoll,
    drakeBlood,
    engravedStone,
    fishSpear,
    garnet,
    greenBambooHat,
    guideBook,
    ironMace,
    koreanFan,
    luckSack,
    nependeathSap,
    panlid,
    pieceOfIce,
    pigsRibbonItem,
    respawnToken,
    risingStar,
    safetyCharm,
    starfallMagicSquare,
    stolenFence,
    sunshinePan,
    workGloves,
} from "./../../item/items";

export const events = [goldRichieMerchant, noob, dueyScenario];

/**
 * Items acquirable from elite/boss battles and treasure boxes
 */
export const ITEMS = [
    safetyCharm,
    drakeBlood,
    nependeathSap,
    coffeePot,
    respawnToken,
    sunshinePan,
    stolenFence,
    panlid,
    luckSack,
    engravedStone,
    guideBook,
    alligatorTube,
    cactus,
    pieceOfIce,
    aquamarine,
    boneHelm,
    amethyst,
    garnet,
    ironMace,
    fishSpear,
    pigsRibbonItem,
    ballerCane,
    greenBambooHat,
    koreanFan,
    risingStar,
    bouquet,
    starfallMagicSquare,
    cursedDoll,
    workGloves,
];
