import { manoEnemy } from "../../enemy/bossSnails";
import {
    axeStump,
    blueMushroom,
    blueSnail,
    bubbling,
    darkStoneGolem,
    egg,
    fireBoar,
    goldenPig,
    golem,
    greenMushroom,
    ironHog,
    jrNecki,
    lupin,
    malady,
    miniKargo,
    octopus,
    orangeMushroom,
    owlTower,
    pig,
    redSnail,
    ribbonPig,
    rockyMask,
    shroom,
    slime,
    snail,
    stirge,
    stump,
    wildBoar,
    wildKargo,
    wraith,
} from "../../enemy/enemy";
import { jrBoogie } from "../../enemy/jrBoogie";
import { tauromacis, taurospear } from "../../enemy/minotaur";
import { mossyMushroom, mossySnail } from "../../enemy/mossyMushroomSnail";
import { moveHeadToTail } from "../../utils";
import { REGIONS } from "../regions";
import { Route, TOWNS } from "../types";
import { curseEye, elliniaGreenMushroom, elliniaHornyMushroom } from "./../../enemy/enemy";
import {
    ancientMixedGolemFight,
    manoFight,
    mushmomFight,
    mutantSnailFight,
    pillagingBoarFight,
    strangePigFight,
    stumpyFight,
} from "./overworldBosses";

export const routePerionSleepywood: Route = {
    id: "perion-sleepywood",
    eliteOptions: {
        numElites: 3,
        numAffixes: 2,
        damageModifier: 2,
    },
    elites: {
        minions: [stump, elliniaGreenMushroom],
        single: [fireBoar, jrBoogie],
        duo: [fireBoar],
        trio: [wildBoar, axeStump],
        squad: [elliniaGreenMushroom],
        special: [
            [null, owlTower, null, owlTower, null],
            [null, miniKargo, wildKargo, miniKargo, null],
            [egg, egg, egg, egg, egg],
            [null, tauromacis, null, taurospear, null],
        ],
    },
    startingTown: TOWNS.PERION,
    region: REGIONS.PERION,
    regionTransition: { atNodeIndex: 3, region: REGIONS.SLEEPYWOOD },
    endingTown: TOWNS.SLEEPYWOOD,
    numNodes: 8,
    cursedTreasureChance: 0.25,
};

export const routeKerningToPerion: Route = {
    id: "kerning-perion",
    specialEnemies: [{ ...goldenPig, maxHP: 28 }],
    elites: {
        minions: [shroom, redSnail, stump],
        single: [fireBoar, rockyMask, jrBoogie],
        duo: [wildBoar, axeStump, wraith],
        trio: [orangeMushroom, octopus, bubbling, stump],
        squad: [redSnail, stirge],
        special: [
            [null, egg, null, egg, null],
            [
                null,
                { ...rockyMask, isElite: true, armor: 150, mesos: 20 },
                null,
                { ...rockyMask, isElite: true, armor: 150, mesos: 20 },
                null,
            ],
        ],
    },
    enemies: [
        [
            stump,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            axeStump,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            stump,
        ],
        [null, orangeMushroom, stump, orangeMushroom, null],
        [null, stump, fireBoar, stump, null],
        [snail, redSnail, octopus, redSnail, snail],
        [null, wildBoar, null, wildBoar, null],
        [octopus, null, stump, null, octopus],
        [null, octopus, redSnail, octopus, null],
        [stump, redSnail, stump, redSnail, stump],
        [
            stump,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            wildBoar,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            stump,
        ],
        [null, axeStump, null, axeStump, null],
        [null, rockyMask, null, rockyMask, null],
        [null, bubbling, null, bubbling, null],
        [
            stirge,
            { ...stirge, abilities: moveHeadToTail(stirge.abilities) },
            stirge,
            { ...stirge, abilities: moveHeadToTail(stirge.abilities) },
            stirge,
        ],
        [null, wraith, { ...wraith, abilities: moveHeadToTail(wraith.abilities) }, wraith, null],
    ],
    multiWaveEnemies: [
        [null, stump, stump, stump, null],
        [blueSnail, redSnail, stump, redSnail, blueSnail],
        [null, redSnail, wildBoar, redSnail, null],
        [null, null, fireBoar, null, null],
        [null, redSnail, axeStump, redSnail, null],
        [null, stump, null, axeStump, null],
        [null, stump, null, wildBoar, null],
        [null, orangeMushroom, null, orangeMushroom, null],
        [null, stump, octopus, stump, null],
        [null, octopus, null, octopus, null],
        [stirge, null, { ...stirge, abilities: moveHeadToTail(stirge.abilities) }, null, stirge],
    ],
    region: REGIONS.KERNING,
    regionTransition: { atNodeIndex: 4, region: REGIONS.PERION },
    numNodes: 9,
    startingTown: TOWNS.KERNING,
    bossNodeIndex: 5,
    bosses: [stumpyFight.id, pillagingBoarFight.id],
    endingTown: TOWNS.PERION,
    cursedTreasureChance: 0.25,
};

const toKerning: Route = {
    id: "to-kerning",
    enemies: [
        [null, octopus, snail, octopus, null],
        [snail, null, orangeMushroom, null, snail],
        [null, snail, octopus, snail, null],
        [null, snail, orangeMushroom, snail, null],
        [null, slime, null, slime, null],
        [null, stump, blueSnail, stump, null],
        [null, pig, null, pig, null],
        [null, pig, null, slime, null],
        [snail, redSnail, blueSnail, redSnail, snail],
        [null, redSnail, redSnail, redSnail, null],
        [snail, shroom, blueSnail, shroom, snail],
        [null, blueSnail, bubbling, blueSnail, null],
    ],
    multiWaveEnemies: [
        [null, null, orangeMushroom, null, null],
        [null, blueSnail, octopus, blueSnail, null],
        [null, snail, pig, snail, null],
        [null, slime, null, slime, null],
        [snail, null, slime, null, snail],
        [snail, blueSnail, redSnail, blueSnail, snail],
        [null, slime, null, redSnail, null],
        [null, shroom, redSnail, shroom, null],
        [null, stump, null, stump, null],
    ],
    specialEnemies: [goldenPig],
    elites: {
        minions: [snail, blueSnail],
        single: [orangeMushroom, octopus, bubbling],
        duo: [stump, slime],
        trio: [redSnail, shroom],
        squad: [snail, blueSnail],
    },
    region: REGIONS.KERNING,
    numNodes: 5,
    endingTown: TOWNS.KERNING,
    next: [],
};

export const routeElliniaSleepywood: Route = {
    id: "ellinia-sleepywood",
    eliteOptions: {
        numElites: 3,
        numAffixes: 2,
        damageModifier: 2,
    },
    elites: {
        minions: [elliniaGreenMushroom, stump],
        single: [lupin, curseEye, ironHog],
        duo: [axeStump, wildBoar],
        trio: [elliniaHornyMushroom, orangeMushroom],
        squad: [elliniaGreenMushroom],
        special: [
            [null, mossyMushroom, null, mossySnail, null],
            [null, malady, null, malady, null],
            [null, taurospear, null, tauromacis, null],
            [null, darkStoneGolem, null, darkStoneGolem, null],
        ],
    },
    enemies: [
        [
            stump,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            axeStump,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            stump,
        ],
        [
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
            ,
            orangeMushroom,
            stump,
            orangeMushroom,
            { ...stump, abilities: moveHeadToTail(stump.abilities) },
        ],
        [orangeMushroom, null, elliniaGreenMushroom, null, orangeMushroom],
        [elliniaGreenMushroom, null, elliniaHornyMushroom, null, elliniaGreenMushroom],
        [elliniaGreenMushroom, stump, orangeMushroom, stump, elliniaGreenMushroom],
        [elliniaGreenMushroom, orangeMushroom, elliniaGreenMushroom, orangeMushroom, elliniaGreenMushroom],
        [null, elliniaHornyMushroom, stump, elliniaHornyMushroom, null],
        [null, elliniaHornyMushroom, orangeMushroom, elliniaHornyMushroom, null],
        [null, elliniaHornyMushroom, greenMushroom, elliniaHornyMushroom, null],
        [null, lupin, null, lupin, null],
        [null, stump, curseEye, stump, null],
        [null, axeStump, stump, axeStump, null],
    ],
    multiWaveEnemies: [
        [null, null, curseEye, null, null],
        [null, redSnail, lupin, redSnail, null],
        [null, stump, axeStump, stump, null],
        [elliniaGreenMushroom, null, elliniaGreenMushroom, null, elliniaGreenMushroom],
        [null, stump, orangeMushroom, stump, null],
        [null, elliniaHornyMushroom, null, elliniaHornyMushroom, null],
        [null, stump, { ...stump, abilities: moveHeadToTail(stump.abilities) }, stump, null],
        [null, stump, elliniaGreenMushroom, stump, null],
        [elliniaGreenMushroom, null, stump, null, elliniaGreenMushroom],
        [null, axeStump, null, axeStump, null],
    ],
    startingTown: TOWNS.ELLINIA,
    region: REGIONS.ELLINIA,
    regionTransition: { atNodeIndex: 3, region: REGIONS.SLEEPYWOOD },
    numNodes: 8,
    endingTown: TOWNS.SLEEPYWOOD,
    cursedTreasureChance: 0.25,
};

export const routeElliniaPerion: Route = {
    id: "ellinia-perion",
    eliteOptions: {
        numElites: 3,
        numAffixes: 2,
    },
    elites: {
        minions: [elliniaGreenMushroom, stump],
        single: [lupin, curseEye, fireBoar],
        duo: [axeStump, wildBoar],
        trio: [elliniaHornyMushroom, orangeMushroom],
        squad: [stump, elliniaGreenMushroom],
        special: [[null, mossyMushroom, null, mossySnail, null]],
    },
    enemies: [
        [stump, stump, axeStump, stump, stump],
        [stump, orangeMushroom, stump, orangeMushroom, stump],
        [orangeMushroom, null, elliniaGreenMushroom, null, orangeMushroom],
        [elliniaGreenMushroom, null, elliniaHornyMushroom, null, elliniaGreenMushroom],
        [elliniaGreenMushroom, stump, orangeMushroom, stump, elliniaGreenMushroom],
        [elliniaGreenMushroom, orangeMushroom, elliniaGreenMushroom, orangeMushroom, elliniaGreenMushroom],
        [null, elliniaHornyMushroom, stump, elliniaHornyMushroom, null],
        [null, elliniaHornyMushroom, orangeMushroom, elliniaHornyMushroom, null],
        [null, elliniaHornyMushroom, greenMushroom, elliniaHornyMushroom, null],
        [null, stump, fireBoar, stump, null],
        [null, lupin, null, lupin, null],
        [null, stump, curseEye, stump, null],
        [null, axeStump, stump, axeStump, null],
        [null, fireBoar, null, fireBoar, null],
    ],
    multiWaveEnemies: [
        [null, null, fireBoar, null, null],
        [null, null, curseEye, null, null],
        [null, redSnail, lupin, redSnail, null],
        [null, stump, axeStump, stump, null],
        [elliniaGreenMushroom, null, elliniaGreenMushroom, null, elliniaGreenMushroom],
        [null, stump, orangeMushroom, stump, null],
        [null, elliniaHornyMushroom, null, elliniaHornyMushroom, null],
        [null, stump, stump, stump, null],
        [null, stump, elliniaGreenMushroom, stump, null],
        [elliniaGreenMushroom, null, stump, null, elliniaGreenMushroom],
        [null, axeStump, null, axeStump, null],
    ],
    startingTown: TOWNS.ELLINIA,
    region: REGIONS.ELLINIA,
    regionTransition: { atNodeIndex: 3, region: REGIONS.PERION },
    numNodes: 9,
    cursedTreasureChance: 0.5,
};

export const routeHenesysEllinia: Route = {
    id: "henesys-ellinia",
    specialEnemies: [{ ...goldenPig, maxHP: 28 }],
    enemies: [
        [stump, redSnail, elliniaGreenMushroom, redSnail, stump],
        [null, null, curseEye, null, null],
        [null, null, ironHog, null, null],
        [null, ribbonPig, null, ribbonPig, null],
        [null, axeStump, stump, axeStump, null],
        [null, lupin, null, lupin, null],
        [elliniaGreenMushroom, elliniaHornyMushroom, redSnail, elliniaHornyMushroom, elliniaGreenMushroom],
        [null, elliniaHornyMushroom, elliniaGreenMushroom, elliniaHornyMushroom, null],
        [null, elliniaHornyMushroom, stump, elliniaHornyMushroom, null],
        [stump, pig, stump, pig, stump],
        [blueSnail, slime, pig, slime, blueSnail],
        [elliniaGreenMushroom, elliniaGreenMushroom, slime, elliniaGreenMushroom, elliniaGreenMushroom],
        [stump, redSnail, stump, redSnail, stump],
        [blueMushroom, blueSnail, orangeMushroom, blueSnail, blueMushroom],
        [
            jrNecki,
            null,
            {
                ...jrNecki,
                abilities: moveHeadToTail(jrNecki.abilities),
            },
            null,
            jrNecki,
        ],
    ],
    multiWaveEnemies: [
        [null, elliniaHornyMushroom, null, elliniaHornyMushroom, null],
        [elliniaGreenMushroom, null, stump, null, elliniaGreenMushroom],
        [blueSnail, blueSnail, blueMushroom, blueSnail, blueSnail],
        [null, stump, stump, stump, null],
        [null, null, lupin, null, null],
        [null, axeStump, null, stump, null],
        [null, pig, redSnail, pig, null],
        [null, slime, null, slime, null],
        [stump, blueSnail, stump, blueSnail, stump],
        [null, elliniaGreenMushroom, elliniaHornyMushroom, elliniaGreenMushroom, null],
    ],
    elites: {
        minions: [redSnail, elliniaGreenMushroom, stump],
        single: [lupin, curseEye],
        duo: [axeStump, orangeMushroom, elliniaHornyMushroom, blueMushroom],
        trio: [elliniaGreenMushroom, pig],
        squad: [redSnail, slime],
        special: [
            [null, null, darkStoneGolem, null, null],
            [null, null, golem, null, null],
        ],
    },
    region: REGIONS.HENESYS,
    regionTransition: { atNodeIndex: 5, region: REGIONS.ELLINIA },
    numNodes: 9,
    startingTown: TOWNS.HENESYS,
    bossNodeIndex: 4,
    bosses: [mushmomFight.id, strangePigFight.id, ancientMixedGolemFight.id],
    endingTown: TOWNS.ELLINIA,
    cursedTreasureChance: 0.25,
};

export const toHenesys: Route = {
    id: "to-henesys",
    enemies: [
        [blueSnail, null, ribbonPig, null, blueSnail],
        [null, orangeMushroom, null, orangeMushroom, null],
        [null, snail, ribbonPig, snail, null],
        [null, slime, null, slime, null],
        [null, pig, blueSnail, pig, null],
        [null, pig, null, pig, null],
        [null, pig, null, slime, null],
        [blueSnail, redSnail, blueSnail, redSnail, blueSnail],
        [null, redSnail, redSnail, redSnail, null],
        [snail, shroom, blueSnail, shroom, snail],
        [blueSnail, blueSnail, blueMushroom, blueSnail, blueSnail],
        [null, blueMushroom, blueSnail, blueMushroom, null],
    ],
    multiWaveEnemies: [
        [null, null, orangeMushroom, null, null],
        [null, null, ribbonPig, null, null],
        [null, blueSnail, pig, blueSnail, null],
        [null, blueSnail, slime, blueSnail, null],
        [snail, null, slime, null, snail],
        [snail, blueSnail, redSnail, blueSnail, snail],
        [null, slime, null, redSnail, null],
        [null, shroom, redSnail, shroom, null],
    ],
    specialEnemies: [goldenPig],
    elites: {
        minions: [snail, blueSnail],
        single: [orangeMushroom, ribbonPig],
        duo: [pig, slime, blueMushroom],
        trio: [redSnail, shroom],
        squad: [snail, blueSnail],
    },
    region: REGIONS.HENESYS,
    numNodes: 5,
    endingTown: TOWNS.HENESYS,
    next: [],
};

export const routeLith: Route = {
    id: "leaving-lith",
    specialEnemies: [goldenPig],
    elites: {
        minions: [snail],
        single: [slime, pig],
        duo: [redSnail],
        trio: [blueSnail, shroom],
        squad: [snail],
        special: [],
    },
    enemies: [
        [snail, blueSnail, redSnail, blueSnail, snail],
        [snail, redSnail, snail, redSnail, snail],
        [null, blueSnail, pig, snail, null],
        [blueSnail, snail, shroom, snail, blueSnail],
        [shroom, null, redSnail, null, shroom],
        [null, slime, null, slime, null],
        [null, redSnail, shroom, redSnail, null],
        [null, shroom, redSnail, shroom, null],
        [null, blueSnail, blueMushroom, blueSnail, null],
        [null, pig, null, pig, null],
        [null, null, orangeMushroom, null, null],
    ],
    multiWaveEnemies: [
        [snail, blueSnail, snail, blueSnail, snail],
        [null, blueSnail, shroom, blueSnail, null],
        [null, shroom, null, shroom, null],
        [null, shroom, null, redSnail, null],
        [null, blueSnail, redSnail, blueSnail, null],
        [null, redSnail, blueSnail, redSnail, null],
        [null, null, pig, null, null],
        [null, null, slime, null, null],
    ],
    region: REGIONS.LITH_HARBOR,
    numNodes: 7,
    bossNodeIndex: 6,
    bosses: [mutantSnailFight.id, manoFight.id],
    next: [toKerning, toHenesys],
};

export const toLith: Route = {
    id: "lith-harbor",
    region: REGIONS.LITH_HARBOR,
    numNodes: 1,
    endingTown: TOWNS.LITH_HARBOR,
    next: [routeLith],
};

export const ROUTE_ID_MAP = [
    routePerionSleepywood,
    routeKerningToPerion,
    toKerning,
    routeElliniaSleepywood,
    routeElliniaPerion,
    routeHenesysEllinia,
    toHenesys,
    routeLith,
    toLith,
].reduce(
    (acc, route) => ({
        ...acc,
        [route.id]: route,
    }),
    {}
);
