import { PLAYER_CLASSES, WARRIOR_SECONDARY_JOBS } from "../Menu/types";
import {
    darkImpale,
    darkSpear,
    darkThirst,
    evilEye,
    evilEyeShock,
    gungnir,
    lordOfDarkness,
    nightshadeExplosion,
    piercingDrive,
    spearSweep,
} from "./warrior/darkKnightAbilities";
import {
    intrepidSlash,
    puncture,
    brandish,
    comboFury,
    chanceStrike,
    parry,
    ragingBlow,
    worldReaver,
    risingRage,
    burningSoulBlade,
} from "./warrior/fighterAbilities";
import {
    bash,
    block,
    shieldStrike,
    slam,
    slashBlast,
    warLeap,
    anger,
    bloodthirst,
    spikedArmor,
    warBanner,
    yell,
    bunchOBricks,
    hammerang,
    ironWill,
    hyperBody,
    sweepingReach,
    sharpen,
    rush,
    berserk,
    closeCombat,
    magicCrash,
    recovery,
    dash,
    ironBody,
    rendingStrike,
    whirlwind,
    rupture,
    bladestorm,
    rally,
    dustDevils,
    doubleTime,
    arsenal,
} from "./warrior/warriorAbilities";
import {
    blast,
    blizzardCharge,
    divineCharge,
    elementalForce,
    flameCharge,
    frostFire,
    judgment,
    lightningCharge,
    parashockGuard,
    shieldMastery,
} from "./warrior/whiteknightAbilities";

export const JOB_CARD_MAP = {
    [PLAYER_CLASSES.WARRIOR]: {
        all: [
            bash,
            warLeap,
            slashBlast,
            block,
            slam,
            anger,
            shieldStrike,
            bloodthirst,
            spikedArmor,
            warBanner,
            yell,
            bunchOBricks,
            hammerang,
            ironWill,
            hyperBody,
            sweepingReach,
            sharpen,
            rush,
            berserk,
            closeCombat,
            recovery,
            magicCrash,
            dash,
            ironBody,
            rendingStrike,
            whirlwind,
            rupture,
            bladestorm,
            rally,
            dustDevils,
            doubleTime,
            arsenal,
        ],
        starters: [warLeap, slashBlast, slashBlast, slam, slam, block, block],
    },
    [WARRIOR_SECONDARY_JOBS.FIGHTER]: {
        onJobUp: [brandish, puncture],
        all: [intrepidSlash, puncture, brandish, comboFury, chanceStrike, parry, ragingBlow, worldReaver, risingRage, burningSoulBlade],
    },
    [WARRIOR_SECONDARY_JOBS.DARK_KNIGHT]: {
        onJobUp: [evilEye, piercingDrive],
        all: [
            evilEye,
            darkImpale,
            darkThirst,
            darkSpear,
            piercingDrive,
            spearSweep,
            evilEyeShock,
            lordOfDarkness,
            gungnir,
            nightshadeExplosion,
        ],
    },
    [WARRIOR_SECONDARY_JOBS.WHITE_KNIGHT]: {
        onJobUp: [flameCharge, blizzardCharge],
        all: [
            flameCharge,
            blizzardCharge,
            lightningCharge,
            blast,
            divineCharge,
            frostFire,
            shieldMastery,
            judgment,
            parashockGuard,
            elementalForce,
        ],
    },
};
