import { MAGICIAN_SECONDARY_JOBS, PLAYER_CLASSES, WARRIOR_SECONDARY_JOBS } from "../Menu/types";
import {
    arcaneAim,
    arcaneChanneling,
    aurora,
    avatarOfTheStars,
    bagFromBeyond,
    chainLightning,
    coldBeam,
    combust,
    conjureTreat,
    copySpell,
    energyBolt,
    feedback,
    fireArrow,
    frostBarrier,
    goutOfFlame,
    greaterBolt,
    greatestBolt,
    ignite,
    magicArmor,
    magicBooster,
    magicClaw,
    magicFang,
    magicGuard,
    metronome,
    moltenLaser,
    mpEater,
    polymorph,
    shatter,
    shootingStars,
    slimmingMuffin,
    teleport,
    temporalBag,
    throwTheBook,
    thunderBolt,
    thunderclap,
    tribolt,
    volatileMagic,
    wishUponAStar,
} from "./magician/magicianAbilities";
import {
    darkImpale,
    darkSpear,
    darkThirst,
    evilEye,
    evilEyeShock,
    gungnir,
    lordOfDarkness,
    nightshadeExplosion,
    piercingDrive,
    spearSweep,
} from "./warrior/darkKnightAbilities";
import {
    brandish,
    burningSoulBlade,
    chanceAttack,
    comboFury,
    intrepidSlash,
    parry,
    puncture,
    ragingBlow,
    risingRage,
    worldReaver,
} from "./warrior/fighterAbilities";
import {
    anger,
    arsenal,
    bash,
    berserk,
    bladedArmor,
    bladestorm,
    block,
    bunchOBricks,
    closeCombat,
    combatOrders,
    dash,
    doubleTime,
    dustDevils,
    hammerang,
    hyperBody,
    ironBody,
    ironWill,
    magicCrash,
    recovery,
    rendingStrike,
    rupture,
    rush,
    sharpen,
    shieldStrike,
    shout,
    slam,
    slashBlast,
    sledge,
    spikedArmor,
    sweepingReach,
    warBanner,
    warLeap,
    whirlwind,
    yell,
} from "./warrior/warriorAbilities";
import {
    blast,
    blizzardCharge,
    divineCharge,
    elementalForce,
    flameCharge,
    frostFire,
    judgment,
    lightningCharge,
    parashockGuard,
    shieldMastery,
} from "./warrior/whiteKnightAbilities";

export const JOB_CARD_MAP = {
    [PLAYER_CLASSES.MAGICIAN]: {
        all: [
            energyBolt,
            magicClaw,
            magicFang,
            tribolt,
            magicArmor,
            magicGuard,
            teleport,
            mpEater,
            arcaneAim,
            thunderclap,
            ignite,
            frostBarrier,
            chainLightning,
            shootingStars,
            wishUponAStar,
            fireArrow,
            conjureTreat,
            avatarOfTheStars,
            greaterBolt,
            throwTheBook,
            magicBooster,
            coldBeam,
            shatter,
            thunderBolt,
            slimmingMuffin,
            aurora,
            feedback,
            metronome,
            arcaneChanneling,
            polymorph,
            goutOfFlame,
            temporalBag,
            greatestBolt,
            copySpell,
            volatileMagic,
            bagFromBeyond,
            moltenLaser,
            combust,
        ],
        starters: [energyBolt, energyBolt, magicClaw, magicClaw, magicFang, magicFang, magicArmor, magicArmor, magicArmor, teleport],
    },
    [MAGICIAN_SECONDARY_JOBS.FIRE_POISON_MAGE]: {
        all: [],
    },
    [MAGICIAN_SECONDARY_JOBS.ICE_LIGHTNING_MAGE]: {
        all: [],
    },
    [MAGICIAN_SECONDARY_JOBS.PRIEST]: {
        all: [],
    },
    [PLAYER_CLASSES.WARRIOR]: {
        all: [
            bash,
            warLeap,
            slashBlast,
            block,
            slam,
            anger,
            shieldStrike,
            shout,
            spikedArmor,
            warBanner,
            yell,
            bunchOBricks,
            hammerang,
            ironWill,
            hyperBody,
            sweepingReach,
            sharpen,
            rush,
            berserk,
            closeCombat,
            recovery,
            magicCrash,
            dash,
            ironBody,
            rendingStrike,
            whirlwind,
            rupture,
            bladestorm,
            combatOrders,
            dustDevils,
            doubleTime,
            arsenal,
            sledge,
            bladedArmor,
        ],
        starters: [warLeap, slashBlast, slashBlast, slam, slam, block, block, block, bash, bash],
    },
    [WARRIOR_SECONDARY_JOBS.FIGHTER]: {
        onJobUp: [brandish, puncture],
        all: [intrepidSlash, puncture, brandish, comboFury, chanceAttack, parry, ragingBlow, worldReaver, risingRage, burningSoulBlade],
    },
    [WARRIOR_SECONDARY_JOBS.DARK_KNIGHT]: {
        onJobUp: [evilEye, piercingDrive],
        all: [
            evilEye,
            darkImpale,
            darkThirst,
            darkSpear,
            piercingDrive,
            spearSweep,
            evilEyeShock,
            lordOfDarkness,
            gungnir,
            nightshadeExplosion,
        ],
    },
    [WARRIOR_SECONDARY_JOBS.WHITE_KNIGHT]: {
        onJobUp: [flameCharge, blizzardCharge],
        all: [
            flameCharge,
            blizzardCharge,
            lightningCharge,
            blast,
            divineCharge,
            frostFire,
            shieldMastery,
            judgment,
            parashockGuard,
            elementalForce,
        ],
    },
};
